# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["test_ci"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!

            # Runs a set of commands using the runners shell
            - name: Run a multi-line script
              run: |
                  echo Add other actions to build,
                  echo test, and deploy your project.
            - name: Run ANOTHER script
              run: echo WEEWOOWEEWOO!
            - name: see ip
              run: curl ifconfig.io
            - name: see df -h
              run: df -h
            - name: see ls
              run: ls -la
            - name: free -h
              run: free -h
            - name: pwd
              run: pwd
            - name: lscpu
              run: lscpu
            - name: check python
              run: python --version
            - name: whoami
              run: whoami

            - name: InstallPython
              uses: actions/setup-python@v4
              with:
                  python-version: "pypy3.9"

            - name: RUN PYTHON SCRIPT
              run: python main.py

            - name: ls
              run: ls -la
            - name: nproc
              run: nproc

            - name: Check for systemctl
              run: |
                  if command -v systemctl &> /dev/null; then
                    echo "systemctl is installed"
                  else
                    echo "systemctl is not installed"
                  fi

            - name: Check for service
              run: |
                  if command -v service &> /dev/null; then
                    echo "service is installed"
                  else
                    echo "service is not installed"
                  fi
            - name:
              run: systemctl status sshd

            - name: genssh
              run: ssh-keygen -f ~/.ssh/id_rsa -P ""
# Install python
# create a new fle
# list files again
